### ISSUE TITLE
Suggestion: Minify the CSS

### ISSUE THREAD

**Issue by Gyomb** [renaudMaupoux/config-site-base-v1.0#10]
Self explanatory ;-)

**Comment by renaudMaupoux** [comment]
I'll use a plugin for it

**Comment by renaudMaupoux** [comment]
Do you know gulp-clean-css?

**Comment by Gyomb** [comment]
For now I used gulp-uglify for the JS, but it the same principle.

**Comment by Gyomb** [comment]
Done on https://github.com/renaudMaupoux/config-site-base-v2.0-master
