### ISSUE TITLE
Suggestion: reorganize the dev environment

### ISSUE THREAD

**Issue by Gyomb** [renaudMaupoux/config-site-base-v1.0#8]
Separate the project in three folder:
* dev/
* test/
* prod/

### dev/
The dev/ folder will contain all the source files (assets sources, scss files). It's where you code.

### test/
The test/ folder is a folder where all your dev/ files are compiled a first time. It's this folder you will test in your browser.
You can already have some optimization done there, but CSS and other code stuff needs to be readable., for testing.

### prod/
The prod/ folder will contain all the content you need to push on your site is stored.
There, everything is optimized, minified and ready to be send to your website.

**Comment by renaudMaupoux** [comment]
ok I'll try to do it. I'll have to duplicate files in test and prod like jquery for exemple and html?

**Comment by Gyomb** [comment]
Yes, but that's a task for Gulp ;-)
That's one of the things I wanted to propose to work on next Monday.

**Comment by renaudMaupoux** [comment]
To do so, I'll have to erase all my files on github

You talked about an app called gitkraken, is it a bridge between git and github or something to visualize all the changes?

**Comment by Gyomb** [comment]
Normally, to use with GitHub, you would modify locally, store your modifications with git and then send them to your GitHub repo.
But we will go through that on Monday. It probably will be our first exercice :-)

**Comment by Gyomb** [comment]
Done on https://github.com/renaudMaupoux/config-site-base-v2.0-master
